- name: "bug"
  description: "Something isn't working"
  color: "d73a4a"
- name: "documentation"
  description: "Improvements or additions to documentation"
  color: "0075ca"
- name: "duplicate"
  description: "This issue or pull request already exists"
  color: "cfd3d7"
- name: "enhancement"
  description: "New feature or request"
  color: "a2eeef"
- name: "good first issue"
  description: "Good for newcomers"
  color: "7057ff"
- name: "help wanted"
  description: "Extra attention is needed"
  color: "008672"
- name: "invalid"
  description: "This doesn't seem right"
  color: "e4e669"
- name: "question"
  description: "Further information is requested"
  color: "d876e3"

## Action labels
- name: "automated pr"
  description: "Automated Pull Request"
  color: "fbca04"
- name: "increment-version"
  description: "Increment Version PR"
  color: "fbca04"
- name: "release"
  description: "Release"
  color: "fbca04"
- name: "release-version"
  description: "Release Version"
  color: "fbca04"
- name: "wontfix"
  description: "Won't fix"
  color: "fbca04"

# Release note labels
- name: "fix"
  color: "d73a4a"
  description: "BugFix"
- name: "feature"
  color: "a2eeef"
  description: "Feature improvement"
- name: "other"
  color: "abdbe3"
  description: "Other"
- name: "other"
  color: "abdbe3"
  description: "Other"
- name: "test"
  color: "008672"
  description: "Test"


